export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'

export const CREATE_PRODUCTS_REQUEST = 'CREATE_PRODUCTS_REQUEST'
export const CREATE_PRODUCTS_SUCCESS = 'CREATE_PRODUCTS_SUCCESS'
export const CREATE_PRODUCTS_FAIL = 'CREATE_PRODUCTS_FAIL'
